# Generated by Django 5.2.10 on 2026-03-08 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Soha nomi')),
            ],
            options={
                'verbose_name': 'Soha',
                'verbose_name_plural': 'Sohalar',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('skills', models.TextField(verbose_name="Ko'nikmalar")),
                ('experience', models.TextField(blank=True, verbose_name='Ish tajribasi')),
                ('education', models.TextField(blank=True, verbose_name="Ta'lim")),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Resume fayli (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Rezyume',
                'verbose_name_plural': 'Rezyumalar',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Lavozim nomi')),
                ('company', models.CharField(max_length=200, verbose_name='Kompaniya nomi')),
                ('city', models.CharField(choices=[('toshkent', 'Toshkent'), ('samarqand', 'Samarqand')], max_length=50, verbose_name='Shahar')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimal maosh ($)')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimal maosh ($)')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('requirements', models.TextField(blank=True, verbose_name='Talablar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='jobs.category', verbose_name='Soha')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Motivatsion xat')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('reviewed', "Ko'rib chiqildi"), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.resume', verbose_name='Rezyume')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.vacancy', verbose_name='Vakansiya')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-applied_at'],
                'unique_together': {('vacancy', 'resume')},
            },
        ),
    ]
