# Generated by Django 5.2.11 on 2026-07-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('candidate', 'Candidate'), ('employer', 'Employer')], max_length=15, null=True)),
            ],
        ),
    ]
