# Generated by Django 5.2.11 on 2026-02-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('internal', 'Internal'), ('national', 'National'), ('international', 'International')], max_length=20)),
                ('required_skills', models.TextField()),
                ('min_experience', models.IntegerField()),
            ],
        ),
    ]
