# Generated by Django 5.2.11 on 2026-07-20 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.TextField(help_text="Nomzod ko'nikmalari (vergul bilan ajratib yozing)")),
                ('experience', models.IntegerField(help_text='Tajriba yillarda')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Ochiq'), ('CLOSED', 'Yopiq')], default='OPEN', help_text='Vakansiya holati', max_length=10)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Vakansiya tavsifi, vazifalar va talablar', null=True)),
                ('industry', models.CharField(blank=True, help_text='Kasb sohasi', max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, help_text="Kasb yo'nalishi", max_length=255, null=True)),
                ('vacant_slots', models.PositiveIntegerField(blank=True, default=1, help_text="Vakant o'rinlari soni", null=True)),
                ('required_skills', models.TextField(blank=True, help_text="Kerakli ko'nikmalar (vergul bilan ajratib yozing)", null=True)),
                ('salary_level', models.CharField(blank=True, help_text='Maosh darajasi (ixtiyoriy matn)', max_length=255, null=True)),
                ('currency', models.CharField(blank=True, choices=[('UZS', 'UZS'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB')], max_length=3, null=True)),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, help_text='Minimal maosh', max_digits=12, null=True)),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, help_text='Maksimal maosh', max_digits=12, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('FULL_TIME', "To'liq bandlik"), ('PART_TIME', 'Qisman bandlik'), ('CONTRACT', 'Shartnoma asosida'), ('INTERNSHIP', 'Amaliyot'), ('FREELANCE', 'Frilans')], max_length=20, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('NO_EXPERIENCE', 'Tajribasiz'), ('UP_TO_1', '1 yilgacha'), ('ONE_TO_THREE', '1-3 yil'), ('THREE_TO_FIVE', '3-5 yil'), ('FIVE_PLUS', '5+ yil')], max_length=20, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('NOT_REQUIRED', 'Muhim emas'), ('SECONDARY', "O'rta"), ('SECONDARY_SPECIAL', "O'rta maxsus"), ('BACHELOR', 'Bakalavr'), ('MASTER', 'Magistr'), ('PHD', 'PhD')], max_length=20, null=True)),
                ('region', models.CharField(blank=True, help_text='Viloyat', max_length=255, null=True)),
                ('district', models.CharField(blank=True, help_text='Tuman / Shahar', max_length=255, null=True)),
                ('work_formats', models.JSONField(blank=True, default=list, help_text='Ish turi (bir nechta qiymat: OFfICE/REMOTE/HYBRID/FIELD)', null=True)),
                ('work_schedule', models.CharField(blank=True, choices=[('6_1', '6/1'), ('5_2', '5/2'), ('4_4', '4/4'), ('4_2', '4/2'), ('3_2', '3/2'), ('2_2', '2/2'), ('2_1', '2/1'), ('WEEKENDS', 'Dam olish kunlarida'), ('FLEXIBLE', 'Erkin'), ('OTHER', 'Boshqa')], max_length=20, null=True)),
                ('daily_hours', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('24', '24'), ('BY_AGREEMENT', "Kelishuv bo'yicha"), ('OTHER', 'Boshqa')], default='8', max_length=20)),
                ('company_address', models.TextField(blank=True, help_text="Korxona manzili (matn ko'rinishida)", null=True)),
                ('map_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('map_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('publish_start', models.DateField(blank=True, null=True)),
                ('publish_end', models.DateField(blank=True, null=True)),
                ('ai_improved_description', models.TextField(blank=True, help_text='AI tomonidan takomillashtirilgan tavsif (ixtiyoriy)', null=True)),
                ('type', models.CharField(blank=True, choices=[('system', 'System'), ('national', 'National'), ('international', 'International')], default='system', max_length=20, null=True)),
                ('min_experience', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='profile.companyprofile')),
            ],
        ),
    ]
