# Generated by Django 5.2.11 on 2026-02-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('national', 'National'), ('international', 'International')], max_length=20),
        ),
    ]
