# Generated by Django 5.2.11 on 2026-03-24 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_candidate_alter_vacancy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='ai_improved_description',
            field=models.TextField(blank=True, help_text='AI tomonidan takomillashtirilgan tavsif (ixtiyoriy)', null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company_address',
            field=models.TextField(blank=True, help_text="Korxona manzili (matn ko'rinishida)", null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(blank=True, choices=[('UZS', 'UZS'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='daily_hours',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('24', '24'), ('BY_AGREEMENT', "Kelishuv bo'yicha"), ('OTHER', 'Boshqa')], default='8', max_length=20),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='district',
            field=models.CharField(blank=True, help_text='Tuman / Shahar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='education_level',
            field=models.CharField(blank=True, choices=[('NOT_REQUIRED', 'Muhim emas'), ('SECONDARY', "O'rta"), ('SECONDARY_SPECIAL', "O'rta maxsus"), ('BACHELOR', 'Bakalavr'), ('MASTER', 'Magistr'), ('PHD', 'PhD')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', "To'liq bandlik"), ('PART_TIME', 'Qisman bandlik'), ('CONTRACT', 'Shartnoma asosida'), ('INTERNSHIP', 'Amaliyot'), ('FREELANCE', 'Frilans')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('NO_EXPERIENCE', 'Tajribasiz'), ('UP_TO_1', '1 yilgacha'), ('ONE_TO_THREE', '1-3 yil'), ('THREE_TO_FIVE', '3-5 yil'), ('FIVE_PLUS', '5+ yil')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='industry',
            field=models.CharField(blank=True, help_text='Kasb sohasi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='map_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='map_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vacancies/photos/'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='publish_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='publish_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='region',
            field=models.CharField(blank=True, help_text='Viloyat', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_from',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimal maosh', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_level',
            field=models.CharField(blank=True, help_text='Maosh darajasi (ixtiyoriy matn)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_to',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maksimal maosh', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='specialization',
            field=models.CharField(blank=True, help_text="Kasb yo'nalishi", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacant_slots',
            field=models.PositiveIntegerField(blank=True, default=1, help_text="Vakant o'rinlari soni", null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_formats',
            field=models.JSONField(blank=True, default=list, help_text='Ish turi (bir nechta qiymat: OFfICE/REMOTE/HYBRID/FIELD)', null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_schedule',
            field=models.CharField(blank=True, choices=[('6_1', '6/1'), ('5_2', '5/2'), ('4_4', '4/4'), ('4_2', '4/2'), ('3_2', '3/2'), ('2_2', '2/2'), ('2_1', '2/1'), ('WEEKENDS', 'Dam olish kunlarida'), ('FLEXIBLE', 'Erkin'), ('OTHER', 'Boshqa')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.IntegerField(help_text='Tajriba yillarda'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.TextField(help_text="Nomzod ko'nikmalari (vergul bilan ajratib yozing)"),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, help_text='Vakansiya tavsifi, vazifalar va talablar', null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='min_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='required_skills',
            field=models.TextField(blank=True, help_text="Kerakli ko'nikmalar (vergul bilan ajratib yozing)", null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='type',
            field=models.CharField(blank=True, choices=[('system', 'System'), ('national', 'National'), ('international', 'International')], default='system', max_length=20, null=True),
        ),
    ]
