# Generated by Django 5.2.11 on 2026-04-01 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('vacancies', '0003_vacancy_ai_improved_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='profile.companyprofile'),
            preserve_default=False,
        ),
    ]
