# Generated by Django 5.2.11 on 2026-05-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_vacancy_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ochiq'), ('CLOSED', 'Yopiq')], default='OPEN', help_text='Vakansiya holati', max_length=10),
        ),
    ]
