# Generated by Django 5.2.11 on 2026-05-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_vacancy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='photo',
        ),
    ]
