# Generated by Django 5.2.11 on 2026-02-14 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpcode_rename_first_name_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqam to'g'ri formatda bo'lishi kerak. Masalan: +998xxxxxxxxx yoki +7xxxxxxxxxx ", regex='^\\+\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam to'g'ri formatda bo'lishi kerak. Masalan: +998xxxxxxxxx yoki +7xxxxxxxxxx ", regex='^\\+\\d{10,15}$')]),
        ),
    ]
