# Generated by Django 5.2.11 on 2026-02-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otpattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('candidate', 'Ish qidiruvchi'), ('employer', 'Ish beruvchi')], max_length=20, null=True),
        ),
    ]
