# Generated by Django 5.2.11 on 2026-03-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_emailverificationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTPCode',
        ),
    ]
