# Generated by Django 5.2.11 on 2026-07-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aloqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('email', models.EmailField(max_length=254, verbose_name='Email pochta')),
                ('shahar', models.CharField(blank=True, max_length=100, verbose_name='Shahar / Viloyat')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkideIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio sayti')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': "Aloqa ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='IshTajribasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompaniya_nomi', models.CharField(max_length=150, verbose_name='Kompaniya nomi')),
                ('lavozim', models.CharField(max_length=150, verbose_name='Lavozim')),
                ('ish_turi', models.CharField(blank=True, max_length=20, verbose_name='Ish turi')),
                ('boshlanish_sanasi', models.DateField(verbose_name='Boshlanish sanasi')),
                ('tugash_sanasi', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('hozir_ishlayapman', models.BooleanField(default=False, verbose_name='Hozir shu yerda ishlayapman')),
                ('tavsif', models.TextField(blank=True, verbose_name='Vazifalar va yutuqlar tavsifi')),
                ('shahar', models.CharField(blank=True, max_length=100, verbose_name='Shahar')),
            ],
            options={
                'verbose_name': 'Ish tajribasi',
                'verbose_name_plural': 'Ish tajribalari',
                'ordering': ['-boshlanish_sanasi'],
            },
        ),
        migrations.CreateModel(
            name='Konikma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Ko'nikma nomi")),
                ('daraja', models.CharField(blank=True, max_length=20, verbose_name='Daraja')),
                ('kategoriya', models.CharField(blank=True, max_length=100, verbose_name='Kategoriya (masalan: Dasturlash tillari, Vositalar)')),
            ],
            options={
                'verbose_name': "Ko'nikma",
                'verbose_name_plural': "Ko'nikmalar",
            },
        ),
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=300, verbose_name='Maqola sarlavhasi')),
                ('nashriyot', models.CharField(blank=True, max_length=200, verbose_name='Nashriyot / Platforma')),
                ('nashr_sanasi', models.DateField(verbose_name='Nashr sanasi')),
                ('havola', models.URLField(blank=True, verbose_name='Maqola havolasi')),
                ('tavsif', models.TextField(blank=True, verbose_name='Qisqacha tavsif')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-nashr_sanasi'],
            },
        ),
        migrations.CreateModel(
            name='Qiziqish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Qiziqish / Hobbi')),
            ],
            options={
                'verbose_name': 'Qiziqish',
                'verbose_name_plural': 'Qiziqishlar',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutaxasislik', models.CharField(blank=True, max_length=50, verbose_name='Mutaxasislik sohasi')),
                ('lavozim', models.CharField(max_length=150, verbose_name='Joriy lavozim/Maqsadli lavozim')),
                ('men_haqimda', models.TextField(blank=True, verbose_name='Men haqimda')),
                ('profil_rasm', models.ImageField(blank=True, null=True, upload_to='resume/rasmlar/', verbose_name='Profil rasmi')),
                ('resume_fayli', models.FileField(blank=True, null=True, upload_to='resume/fayllar/', verbose_name='Resume fayli')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumelar',
            },
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Sertifikat nomi')),
                ('tashkilot', models.CharField(max_length=200, verbose_name='Bergan tashkilot')),
                ('berilgan_sana', models.DateField(verbose_name='Berilgan sana')),
                ('amal_qilish_muddati', models.DateField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('muddatsiz', models.BooleanField(default=False, verbose_name='Muddatsiz')),
                ('sertifikat_id', models.CharField(blank=True, max_length=100, verbose_name='Sertifikat ID raqami')),
                ('havola', models.URLField(blank=True, verbose_name='Tasdiqlash havolasi')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-berilgan_sana'],
            },
        ),
        migrations.CreateModel(
            name='Talim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muassasa_nomi', models.CharField(max_length=200, verbose_name="Ta'lim muassasasi nomi")),
                ('daraja', models.CharField(blank=True, max_length=20, verbose_name="Ta'lim darajasi")),
                ('mutaxassislik', models.CharField(max_length=200, verbose_name="Mutaxassislik / Yo'nalish")),
                ('boshlanish_yili', models.PositiveIntegerField(verbose_name='Boshlanish yili')),
                ('tugash_yili', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tugash yili')),
                ('hozir_oqiyapman', models.BooleanField(default=False, verbose_name="Hozir o'qiyapman")),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name="GPA / O'zlashtirish")),
            ],
            options={
                'verbose_name': "Ta'lim",
                'verbose_name_plural': "Ta'lim ma'lumotlari",
                'ordering': ['-boshlanish_yili'],
            },
        ),
        migrations.CreateModel(
            name='Til',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('til_nomi', models.CharField(max_length=50, verbose_name='Til nomi')),
                ('daraja', models.CharField(blank=True, max_length=20, verbose_name='Bilish darajasi')),
            ],
            options={
                'verbose_name': 'Til',
                'verbose_name_plural': 'Tillar',
            },
        ),
        migrations.CreateModel(
            name='Yutuq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Yutuq nomi')),
                ('tashkilot', models.CharField(blank=True, max_length=200, verbose_name='Bergan tashkilot')),
                ('sana', models.DateField(blank=True, null=True, verbose_name='Sana')),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Yutuq',
                'verbose_name_plural': 'Yutuqlar',
                'ordering': ['-sana'],
            },
        ),
    ]
