# Generated by Django 5.2.11 on 2026-04-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='yangilangan',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
