# Generated by Django 5.2.11 on 2026-07-20 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='foydalanuvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='qiziqish',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qiziqishlar', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AddField(
            model_name='maqola',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maqolalar', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AddField(
            model_name='konikma',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konikmalar', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AddField(
            model_name='ishtajribasi',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ish_tajribalari', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AddField(
            model_name='aloqa',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aloqa', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AddField(
            model_name='sertifikat',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikatlar', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AddField(
            model_name='talim',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talim_malumotlari', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AddField(
            model_name='til',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tillar', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AddField(
            model_name='yutuq',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yutuqlar', to='resume.resume', verbose_name='Resume'),
        ),
    ]
