# Generated by Django 5.2.11 on 2026-04-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_yangilangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishtajribasi',
            name='ish_turi',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ish turi'),
        ),
        migrations.AlterField(
            model_name='konikma',
            name='daraja',
            field=models.CharField(blank=True, max_length=20, verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='mutaxasislik',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mutaxasislik sohasi'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='yangilangan',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='talim',
            name='daraja',
            field=models.CharField(blank=True, max_length=20, verbose_name="Ta'lim darajasi"),
        ),
        migrations.AlterField(
            model_name='til',
            name='daraja',
            field=models.CharField(blank=True, max_length=20, verbose_name='Bilish darajasi'),
        ),
    ]
