# Generated by Django 5.2.11 on 2026-03-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Telegram havola')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram havola')),
            ],
            options={
                'verbose_name': 'Aloqa kontakti',
                'verbose_name_plural': 'Aloqa kontaktlari',
            },
        ),
        migrations.CreateModel(
            name='PlatformStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqt')),
                ('step_number', models.PositiveIntegerField(verbose_name='Qadam tartibi')),
                ('title', models.CharField(max_length=200, verbose_name='Qadam nomi')),
                ('description', models.TextField(verbose_name='Qadam tavsifi')),
            ],
            options={
                'verbose_name': 'Platforma qadami',
                'verbose_name_plural': 'Platforma qadamlari',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqt')),
                ('name', models.CharField(max_length=100, verbose_name='Tarif nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='Valyuta')),
                ('features', models.TextField(help_text='Imkoniyatlarni yangi qatordan yozing', verbose_name='Imkoniyatlar')),
            ],
            options={
                'verbose_name': 'Tarif rejasi',
                'verbose_name_plural': 'Tarif rejalari',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqt')),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(verbose_name='Mahsulot tavsifi')),
                ('icon', models.ImageField(upload_to='products/', verbose_name='Ikonka')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='TeamAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Jamoa haqida batafsil')),
                ('experience_years', models.PositiveIntegerField(default=1, verbose_name='Tajriba yili')),
                ('team_photo', models.ImageField(upload_to='team_general/', verbose_name='Jamoaviy rasm')),
            ],
            options={
                'verbose_name': "Jamoa ma'lumoti",
                'verbose_name_plural': "Jamoa ma'lumotlari",
            },
        ),
    ]
