# Generated by Django 5.2.11 on 2026-05-11 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users1', '0001_initial'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterviewtoken',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_interview_tokens', to='vacancies.vacancy'),
        ),
        migrations.AddField(
            model_name='telegramlinktoken',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Agar token avvaldan mavjud foydalanuvchi uchun yaratilgan bo'lsa", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
