# Generated by Django 5.2.11 on 2026-05-03 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1', '0003_telegram_tokens_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramlinktoken',
            name='chat_id',
            field=models.CharField(blank=True, help_text='Bot tomonidan uzatiladigan Telegram chat ID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='telegramlinktoken',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Agar token avvaldan mavjud foydalanuvchi uchun yaratilgan bo'lsa", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
